"""initial schema

Revision ID: 204863eceb4b
Revises: 
Create Date: 2026-08-23 02:15:49.682526
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '204863eceb4b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('properties', sa.JSON(), nullable=False),
    sa.Column('app_version', sa.String(length=32), nullable=True),
    sa.Column('platform', sa.String(length=16), nullable=True),
    sa.Column('client_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analytics_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analytics_events_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_events_user_id'), ['user_id'], unique=False)

    op.create_table('idempotency_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('endpoint', sa.String(length=120), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'endpoint', 'key', name='uq_idempotency')
    )
    with op.batch_alter_table('idempotency_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_idempotency_records_user_id'), ['user_id'], unique=False)

    op.create_table('scenarios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scenario_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('primary_skill', sa.String(length=32), nullable=False),
    sa.Column('secondary_skills', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scenario_id', 'version', name='uq_scenario_version')
    )
    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scenarios_level'), ['level'], unique=False)
        batch_op.create_index(batch_op.f('ix_scenarios_primary_skill'), ['primary_skill'], unique=False)
        batch_op.create_index(batch_op.f('ix_scenarios_scenario_id'), ['scenario_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scenarios_status'), ['status'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('apple_subject', sa.String(length=255), nullable=True),
    sa.Column('dev_subject', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('onboarding_status', sa.String(length=32), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('apple_subject'),
    sa.UniqueConstraint('dev_subject')
    )
    op.create_table('assessment_responses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=64), nullable=False),
    sa.Column('choice_id', sa.String(length=64), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'item_id', name='uq_assessment_user_item')
    )
    with op.batch_alter_table('assessment_responses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessment_responses_user_id'), ['user_id'], unique=False)

    op.create_table('learning_path_assignments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('local_date', sa.String(length=10), nullable=False),
    sa.Column('day_index', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.String(length=64), nullable=False),
    sa.Column('scenario_version', sa.Integer(), nullable=False),
    sa.Column('path_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'local_date', name='uq_assignment_user_date')
    )
    with op.batch_alter_table('learning_path_assignments', schema=None) as batch_op:
        batch_op.create_index('ix_assignment_user_status', ['user_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_path_assignments_user_id'), ['user_id'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('skill_assessments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('scenario_id', sa.String(length=64), nullable=True),
    sa.Column('attempt_id', sa.String(length=36), nullable=True),
    sa.Column('skill_key', sa.String(length=32), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('reason_code', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('skill_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skill_assessments_attempt_id'), ['attempt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_skill_assessments_user_id'), ['user_id'], unique=False)

    op.create_table('skill_scores',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('skill_key', sa.String(length=32), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'skill_key', name='uq_skill_user')
    )
    with op.batch_alter_table('skill_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skill_scores_user_id'), ['user_id'], unique=False)

    op.create_table('user_profiles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('goal', sa.String(length=48), nullable=True),
    sa.Column('starting_level', sa.String(length=16), nullable=True),
    sa.Column('current_level', sa.String(length=16), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('total_xp', sa.Integer(), nullable=False),
    sa.Column('streak_count', sa.Integer(), nullable=False),
    sa.Column('path_version', sa.Integer(), nullable=False),
    sa.Column('focus_skills', sa.JSON(), nullable=False),
    sa.Column('entitlement', sa.String(length=16), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('xp_ledger_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('attempt_id', sa.String(length=36), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=48), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id', 'reason', name='uq_xp_attempt_reason')
    )
    with op.batch_alter_table('xp_ledger_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_xp_ledger_entries_user_id'), ['user_id'], unique=False)

    op.create_table('challenge_attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('assignment_id', sa.String(length=36), nullable=False),
    sa.Column('scenario_id', sa.String(length=64), nullable=False),
    sa.Column('scenario_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('selected_option_id', sa.String(length=64), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('draft_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('evidence_points', sa.Integer(), nullable=True),
    sa.Column('decision_points', sa.Integer(), nullable=True),
    sa.Column('rationale_points', sa.Integer(), nullable=True),
    sa.Column('communication_points', sa.Integer(), nullable=True),
    sa.Column('final_score', sa.Integer(), nullable=True),
    sa.Column('xp_awarded', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['learning_path_assignments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assignment_id', name='uq_attempt_assignment')
    )
    with op.batch_alter_table('challenge_attempts', schema=None) as batch_op:
        batch_op.create_index('ix_attempt_user_status', ['user_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_challenge_attempts_user_id'), ['user_id'], unique=False)

    op.create_table('evidence_interactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('attempt_id', sa.String(length=36), nullable=False),
    sa.Column('evidence_card_id', sa.String(length=64), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['challenge_attempts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id', 'evidence_card_id', name='uq_evidence_attempt')
    )
    with op.batch_alter_table('evidence_interactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_interactions_attempt_id'), ['attempt_id'], unique=False)

    op.create_table('feedback_evaluations',
    sa.Column('attempt_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('consequence_snapshot', sa.Text(), nullable=False),
    sa.Column('option_label_snapshot', sa.String(length=120), nullable=False),
    sa.Column('ai_json', sa.JSON(), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=True),
    sa.Column('model_id', sa.String(length=120), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('provider_attempts', sa.Integer(), nullable=False),
    sa.Column('needs_retry', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['challenge_attempts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('attempt_id')
    )
    with op.batch_alter_table('feedback_evaluations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_evaluations_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_evaluations_user_id'), ['user_id'], unique=False)

    op.create_table('feedback_ratings',
    sa.Column('attempt_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('rating', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['challenge_attempts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('attempt_id')
    )
    with op.batch_alter_table('feedback_ratings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_ratings_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback_ratings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_ratings_user_id'))

    op.drop_table('feedback_ratings')
    with op.batch_alter_table('feedback_evaluations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_evaluations_user_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_evaluations_status'))

    op.drop_table('feedback_evaluations')
    with op.batch_alter_table('evidence_interactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_interactions_attempt_id'))

    op.drop_table('evidence_interactions')
    with op.batch_alter_table('challenge_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_challenge_attempts_user_id'))
        batch_op.drop_index('ix_attempt_user_status')

    op.drop_table('challenge_attempts')
    with op.batch_alter_table('xp_ledger_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_xp_ledger_entries_user_id'))

    op.drop_table('xp_ledger_entries')
    op.drop_table('user_profiles')
    with op.batch_alter_table('skill_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skill_scores_user_id'))

    op.drop_table('skill_scores')
    with op.batch_alter_table('skill_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skill_assessments_user_id'))
        batch_op.drop_index(batch_op.f('ix_skill_assessments_attempt_id'))

    op.drop_table('skill_assessments')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_token_hash'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('learning_path_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_path_assignments_user_id'))
        batch_op.drop_index('ix_assignment_user_status')

    op.drop_table('learning_path_assignments')
    with op.batch_alter_table('assessment_responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessment_responses_user_id'))

    op.drop_table('assessment_responses')
    op.drop_table('users')
    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scenarios_status'))
        batch_op.drop_index(batch_op.f('ix_scenarios_scenario_id'))
        batch_op.drop_index(batch_op.f('ix_scenarios_primary_skill'))
        batch_op.drop_index(batch_op.f('ix_scenarios_level'))

    op.drop_table('scenarios')
    with op.batch_alter_table('idempotency_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_idempotency_records_user_id'))

    op.drop_table('idempotency_records')
    with op.batch_alter_table('analytics_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analytics_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_analytics_events_name'))

    op.drop_table('analytics_events')
    # ### end Alembic commands ###
